### ISSUE TITLE
Caught unknown exception authenticating request signature

### ISSUE THREAD

**Issue by rcssdy** [TinEye/pytineye#12]
When performing an image search, I'm continuously receiving the error:

```
pytineye.exceptions.TinEyeAPIError: APIError:
code    = 401
message = ['AUTHENTICATION_ERROR', 'Caught unknown exception authenticating request signature']
```

A single image search goes through perfectly fine, but the remaining image searches do not. We have many searches remaining on our account, and the API credentials are perfectly fine too. Any reason why?

**Comment by jgould22** [comment]
Having discussed this in other channels it appears that this is caused when pytineye is used in conjunction with Celery/Django

It may be related to https://github.com/urllib3/urllib3/issues/850

However pytineye is not thread safe.

I am going to close this issue unless there is any more to be added
