### ISSUE TITLE
Unable to find the zip file

### ISSUE THREAD

**Issue by aprativa** [TinEye/pytineye#13]
Hi,

I'm trying to download the package using wget but it gives me a 404 error. Was wondering if you could help fix this. Thank you!

**Comment by JonathanGuberman** [comment]
Hi @aprativa . It looks like github changed the URL of the zip at some point. The correct URL is:

https://github.com/TinEye/pytineye/archive/main.zip

You can also find this by clicking on the green "code" button in the top right of the project page and selecting "Download ZIP".

Thanks for pointing this out, we'll be sure to update the docs to reflect the change.

**Comment by aprativa** [comment]
Perfect, thank you!
